jnosql.document.database=Smartirrigation
jnosql.mongodb.host=localhost:27017
argon2.saltLength=32
argon2.hashLength=128
argon2.iterations=23
argon2.memory=97579
argon2.threadNumber=2
key.pair.lifetime.duration=10800
key.pair.cache.size=3
jwtTokenValidity=2020
jwtIssuer=smartirrigation.me
jwtAudience=smartirrigation.me
jwtClaimRoles=groups
jwtSecret=Enis2026
jwtAlias=jwt

##MQTT CONFIG
mqtt.broker.broker=tcp://localhost:1883
mqtt.broker.clientId=Smartirrigation
mqtt.broker.username=molka
mqtt.broker.password=molka123
jwtKeystore=C:/wildfly/wildfly-40.0.0.Beta1/standalone/configuration/jwt.keystore
jwtKeystorePassword=Enis2026
